<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Language;
class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Language::insert(array(
            array('id' => '1', 'name' => 'Aboriginal English, so described', 'code' => 'AE', 'description' => 'A dialect of English used by Aboriginal Australians', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '2', 'name' => 'Acehnese', 'code' => 'AC', 'description' => 'A language spoken by the Acehnese people of Indonesia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '3', 'name' => 'Acholi', 'code' => 'ACH', 'description' => 'A Luo-Nilotic language spoken by the Acholi people', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '4', 'name' => 'Adnymathanha', 'code' => 'AD', 'description' => 'A language of the Adnyamathanha people of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '5', 'name' => 'African Languages', 'code' => 'AF', 'description' => 'Languages spoken on the African continent', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '6', 'name' => 'African Languages, nec', 'code' => 'AFN', 'description' => 'Other African languages not elsewhere classified', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '7', 'name' => 'Afrikaans', 'code' => 'AFK', 'description' => 'A West Germanic language spoken in South Africa and Namibia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '8', 'name' => 'Akan', 'code' => 'AK', 'description' => 'A Central Tano language spoken in Ghana', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '9', 'name' => 'Alawa', 'code' => 'ALW', 'description' => 'A language of the Northern Territory of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '10', 'name' => 'Albanian', 'code' => 'ALB', 'description' => 'An Indo-European language spoken by the Albanians', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '11', 'name' => 'Alngith', 'code' => 'ALN', 'description' => 'A language of the Cape York Peninsula in Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '12', 'name' => 'Alyawarr', 'code' => 'ALY', 'description' => 'A language spoken in the Northern Territory of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '13', 'name' => 'American Languages', 'code' => 'AML', 'description' => 'Languages spoken by indigenous peoples of the Americas', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '14', 'name' => 'Amharic', 'code' => 'AMH', 'description' => 'A Semitic language spoken in Ethiopia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '15', 'name' => 'Amurdak', 'code' => 'AMU', 'description' => 'A language spoken in the Northern Territory of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '16', 'name' => 'Anindilyakwa', 'code' => 'ANI', 'description' => 'A language spoken by the Anindilyakwa people of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '17', 'name' => 'Anmatyerr', 'code' => 'ANM', 'description' => 'A language spoken by the Anmatyerr people of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '18', 'name' => 'Anmatyerr, nec', 'code' => 'ANX', 'description' => 'Other Anmatyerr languages not elsewhere classified', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '19', 'name' => 'Antekerrepenh', 'code' => 'ANT', 'description' => 'A language spoken in the Northern Territory of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '20', 'name' => 'Antikarinya', 'code' => 'ANK', 'description' => 'A language spoken in South Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '21', 'name' => 'Anuak', 'code' => 'ANU', 'description' => 'A Nilotic language spoken by the Anuak people', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '22', 'name' => 'Arabana', 'code' => 'ARB', 'description' => 'A language of the Arabana people of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '23', 'name' => 'Arabic', 'code' => 'ARA', 'description' => 'A Semitic language spoken widely across the Arab world', 'direction' => 'rtl', 'default' => '', 'status' => 'A'),
            array('id' => '24', 'name' => 'Arandic', 'code' => 'ARD', 'description' => 'Languages spoken by the Arrernte people of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '25', 'name' => 'Arandic, nec', 'code' => 'ARN', 'description' => 'Other Arandic languages not elsewhere classified', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '26', 'name' => 'Aranda', 'code' => 'ARA', 'description' => 'A language spoken by the Aranda people of Australia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '27', 'name' => 'Armenian', 'code' => 'ARM', 'description' => 'An Indo-European language spoken by the Armenians', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '28', 'name' => 'Assyrian', 'code' => 'ASY', 'description' => 'A dialect of Neo-Aramaic spoken by the Assyrian people', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '29', 'name' => 'Atayal', 'code' => 'ATY', 'description' => 'An Austronesian language spoken in Taiwan', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '30', 'name' => 'Australian Languages', 'code' => 'AUL', 'description' => 'Languages spoken by indigenous Australians', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '31', 'name' => 'Aymara', 'code' => 'AYM', 'description' => 'A language spoken by the Aymara people of the Andes', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '32', 'name' => 'Azeri', 'code' => 'AZE', 'description' => 'A language spoken in Azerbaijan', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '33', 'name' => 'Balinese', 'code' => 'BAL', 'description' => 'An Austronesian language spoken by the Balinese people', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '34', 'name' => 'Bambara', 'code' => 'BAM', 'description' => 'A Mande language spoken in Mali', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '35', 'name' => 'Basque', 'code' => 'BAS', 'description' => 'A language spoken by the Basque people of Spain and France', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '36', 'name' => 'Belarusian', 'code' => 'BEL', 'description' => 'An East Slavic language spoken in Belarus', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '37', 'name' => 'Bemba', 'code' => 'BEM', 'description' => 'A Bantu language spoken in Zambia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '38', 'name' => 'Bengali', 'code' => 'BEN', 'description' => 'An Indo-Aryan language spoken in Bangladesh and India', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '39', 'name' => 'Bislama', 'code' => 'BIS', 'description' => 'A creole language spoken in Vanuatu', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '40', 'name' => 'Bosnian', 'code' => 'BOS', 'description' => 'A South Slavic language spoken in Bosnia and Herzegovina', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '41', 'name' => 'Breton', 'code' => 'BRE', 'description' => 'A Celtic language spoken in Brittany, France', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '42', 'name' => 'Bulgarian', 'code' => 'BUL', 'description' => 'A South Slavic language spoken in Bulgaria', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '43', 'name' => 'Burmese', 'code' => 'BUR', 'description' => 'A Sino-Tibetan language spoken in Myanmar', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '44', 'name' => 'Catalan', 'code' => 'CAT', 'description' => 'A Romance language spoken in Catalonia, Spain', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '45', 'name' => 'Cebuano', 'code' => 'CEB', 'description' => 'An Austronesian language spoken in the Philippines', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '46', 'name' => 'Chechen', 'code' => 'CHE', 'description' => 'A Northeast Caucasian language spoken in Chechnya', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '47', 'name' => 'Cherokee', 'code' => 'CHR', 'description' => 'An Iroquoian language spoken by the Cherokee people', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '48', 'name' => 'Chichewa', 'code' => 'CHI', 'description' => 'A Bantu language spoken in Malawi', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '49', 'name' => 'Chinese', 'code' => 'CHN', 'description' => 'A group of related but distinct language varieties', 'direction' => 'ltr', 'default' => '', 'status' => 'A'),
            array('id' => '50', 'name' => 'Chinook', 'code' => 'CHO', 'description' => 'A group of languages spoken by the Chinook people', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '51', 'name' => 'Chipewyan', 'code' => 'CHP', 'description' => 'An Athabaskan language spoken in Canada', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '52', 'name' => 'Choctaw', 'code' => 'CHT', 'description' => 'A Muskogean language spoken by the Choctaw people', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '53', 'name' => 'Cree', 'code' => 'CRE', 'description' => 'A group of Algonquian languages spoken in Canada', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '54', 'name' => 'Creole', 'code' => 'CRL', 'description' => 'A stable, natural language developed from a mixture of different languages', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '55', 'name' => 'Croatian', 'code' => 'CRO', 'description' => 'A South Slavic language spoken in Croatia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '56', 'name' => 'Czech', 'code' => 'CZE', 'description' => 'A West Slavic language spoken in the Czech Republic', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '57', 'name' => 'Danish', 'code' => 'DAN', 'description' => 'A North Germanic language spoken in Denmark', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '58', 'name' => 'Dinka', 'code' => 'DIN', 'description' => 'A Nilotic language spoken in South Sudan', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '59', 'name' => 'Dutch', 'code' => 'DUT', 'description' => 'A West Germanic language spoken in the Netherlands', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '60', 'name' => 'Dzongkha', 'code' => 'DZO', 'description' => 'A Sino-Tibetan language spoken in Bhutan', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '61', 'name' => 'Edo', 'code' => 'EDO', 'description' => 'A language spoken in Nigeria', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '62', 'name' => 'Estonian', 'code' => 'EST', 'description' => 'A Finno-Ugric language spoken in Estonia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '63', 'name' => 'Faroese', 'code' => 'FAR', 'description' => 'A North Germanic language spoken in the Faroe Islands', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '64', 'name' => 'Fijian', 'code' => 'FIJ', 'description' => 'An Austronesian language spoken in Fiji', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '65', 'name' => 'Finnish', 'code' => 'FIN', 'description' => 'A Finno-Ugric language spoken in Finland', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '66', 'name' => 'Flemish', 'code' => 'FLE', 'description' => 'A variety of Dutch spoken in Belgium', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '67', 'name' => 'French', 'code' => 'FRE', 'description' => 'A Romance language spoken in France and other countries', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '68', 'name' => 'Friulian', 'code' => 'FRI', 'description' => 'A Romance language spoken in Italy', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '69', 'name' => 'Gaelic', 'code' => 'GAE', 'description' => 'A Celtic language spoken in Scotland', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '70', 'name' => 'Galician', 'code' => 'GAL', 'description' => 'A Romance language spoken in Galicia, Spain', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '71', 'name' => 'Georgian', 'code' => 'GEO', 'description' => 'A South Caucasian language spoken in Georgia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '72', 'name' => 'German', 'code' => 'GER', 'description' => 'A West Germanic language spoken in Germany', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '73', 'name' => 'Greek', 'code' => 'GRE', 'description' => 'An Indo-European language spoken in Greece', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '74', 'name' => 'Guarani', 'code' => 'GUA', 'description' => 'A Tupi-Guarani language spoken in Paraguay', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '75', 'name' => 'Gujarati', 'code' => 'GUJ', 'description' => 'An Indo-Aryan language spoken in Gujarat, India', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '76', 'name' => 'Haitian Creole', 'code' => 'HAI', 'description' => 'A French-based creole language spoken in Haiti', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '77', 'name' => 'Hausa', 'code' => 'HAU', 'description' => 'A Chadic language spoken in Nigeria', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '78', 'name' => 'Hawaiian', 'code' => 'HAW', 'description' => 'A Polynesian language spoken in Hawaii', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '79', 'name' => 'Hebrew', 'code' => 'HEB', 'description' => 'A Semitic language spoken in Israel', 'direction' => 'rtl', 'default' => '', 'status' => 'A'),
            array('id' => '80', 'name' => 'Hindi', 'code' => 'HIN', 'description' => 'An Indo-Aryan language spoken in India', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '81', 'name' => 'Hmong', 'code' => 'HMO', 'description' => 'A Hmong-Mien language spoken in China, Vietnam, Laos, and Thailand', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '82', 'name' => 'Hungarian', 'code' => 'HUN', 'description' => 'A Finno-Ugric language spoken in Hungary', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '83', 'name' => 'Icelandic', 'code' => 'ICE', 'description' => 'A North Germanic language spoken in Iceland', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '84', 'name' => 'Igbo', 'code' => 'IGB', 'description' => 'A Niger-Congo language spoken in Nigeria', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '85', 'name' => 'Ilocano', 'code' => 'ILO', 'description' => 'An Austronesian language spoken in the Philippines', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '86', 'name' => 'Indonesian', 'code' => 'IND', 'description' => 'An Austronesian language spoken in Indonesia', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '87', 'name' => 'Inuktitut', 'code' => 'INU', 'description' => 'An Inuit language spoken in Canada', 'direction' => '', 'default' => '', 'status' => 'A'),
            array('id' => '88', 'name' => 'Irish', 'code' => 'IRI', 'description' => 'A Celtic language spoken in Ireland', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '89', 'name' => 'Italian', 'code' => 'ITA', 'description' => 'A Romance language spoken in Italy', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '90', 'name' => 'Japanese', 'code' => 'JAP', 'description' => 'A language spoken in Japan', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '91', 'name' => 'Javanese', 'code' => 'JAV', 'description' => 'An Austronesian language spoken in Indonesia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '92', 'name' => 'Kannada', 'code' => 'KAN', 'description' => 'A Dravidian language spoken in India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '93', 'name' => 'Kashmiri', 'code' => 'KAS', 'description' => 'An Indo-Aryan language spoken in Kashmir', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '94', 'name' => 'Kazakh', 'code' => 'KAZ', 'description' => 'A Turkic language spoken in Kazakhstan', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '95', 'name' => 'Khmer', 'code' => 'KHM', 'description' => 'A Mon-Khmer language spoken in Cambodia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '96', 'name' => 'Korean', 'code' => 'KOR', 'description' => 'A language spoken in Korea', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '97', 'name' => 'Kurdish', 'code' => 'KUR', 'description' => 'An Indo-Iranian language spoken by Kurds', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '98', 'name' => 'Kyrgyz', 'code' => 'KYR', 'description' => 'A Turkic language spoken in Kyrgyzstan', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '99', 'name' => 'Lao', 'code' => 'LAO', 'description' => 'A Kra-Dai language spoken in Laos', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '100', 'name' => 'Latvian', 'code' => 'LAT', 'description' => 'A Baltic language spoken in Latvia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '101', 'name' => 'Lithuanian', 'code' => 'LIT', 'description' => 'A Baltic language spoken in Lithuania', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '102', 'name' => 'Luxembourgish', 'code' => 'LUX', 'description' => 'A West Germanic language spoken in Luxembourg', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '103', 'name' => 'Macedonian', 'code' => 'MAC', 'description' => 'A South Slavic language spoken in North Macedonia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '104', 'name' => 'Malagasy', 'code' => 'MAL', 'description' => 'An Austronesian language spoken in Madagascar', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '105', 'name' => 'Malay', 'code' => 'MAY', 'description' => 'An Austronesian language spoken in Malaysia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '106', 'name' => 'Malayalam', 'code' => 'MAL', 'description' => 'A Dravidian language spoken in India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '107', 'name' => 'Maltese', 'code' => 'MAL', 'description' => 'A Semitic language spoken in Malta', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '108', 'name' => 'Maori', 'code' => 'MAO', 'description' => 'A Polynesian language spoken in New Zealand', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '109', 'name' => 'Marathi', 'code' => 'MAR', 'description' => 'An Indo-Aryan language spoken in India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '110', 'name' => 'Mongolian', 'code' => 'MON', 'description' => 'A Mongolic language spoken in Mongolia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '111', 'name' => 'Nepali', 'code' => 'NEP', 'description' => 'An Indo-Aryan language spoken in Nepal', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '112', 'name' => 'Norwegian', 'code' => 'NOR', 'description' => 'A North Germanic language spoken in Norway', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '113', 'name' => 'Oriya', 'code' => 'ORI', 'description' => 'An Indo-Aryan language spoken in India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '114', 'name' => 'Pashto', 'code' => 'PAS', 'description' => 'An Iranian language spoken in Afghanistan and Pakistan', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '115', 'name' => 'Persian', 'code' => 'PER', 'description' => 'An Iranian language spoken in Iran', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '116', 'name' => 'Polish', 'code' => 'POL', 'description' => 'A West Slavic language spoken in Poland', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '117', 'name' => 'Portuguese', 'code' => 'POR', 'description' => 'A Romance language spoken in Portugal and Brazil', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '118', 'name' => 'Punjabi', 'code' => 'PUN', 'description' => 'An Indo-Aryan language spoken in Punjab, India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '119', 'name' => 'Quechua', 'code' => 'QUE', 'description' => 'An indigenous language spoken in the Andes', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '120', 'name' => 'Romanian', 'code' => 'ROM', 'description' => 'A Romance language spoken in Romania', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '121', 'name' => 'Russian', 'code' => 'RUS', 'description' => 'An East Slavic language spoken in Russia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '122', 'name' => 'Samoan', 'code' => 'SAM', 'description' => 'A Polynesian language spoken in Samoa', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '123', 'name' => 'Sanskrit', 'code' => 'SAN', 'description' => 'An ancient Indo-Aryan language', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '124', 'name' => 'Serbian', 'code' => 'SER', 'description' => 'A South Slavic language spoken in Serbia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '125', 'name' => 'Sindhi', 'code' => 'SIN', 'description' => 'An Indo-Aryan language spoken in Pakistan and India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '126', 'name' => 'Sinhala', 'code' => 'SIN', 'description' => 'An Indo-Aryan language spoken in Sri Lanka', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '127', 'name' => 'Slovak', 'code' => 'SLO', 'description' => 'A West Slavic language spoken in Slovakia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '128', 'name' => 'Slovene', 'code' => 'SLV', 'description' => 'A South Slavic language spoken in Slovenia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '129', 'name' => 'Somali', 'code' => 'SOM', 'description' => 'A Cushitic language spoken in Somalia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '130', 'name' => 'Spanish', 'code' => 'SPA', 'description' => 'A Romance language spoken in Spain and Latin America', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '131', 'name' => 'Sundanese', 'code' => 'SUN', 'description' => 'A language spoken in Indonesia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '132', 'name' => 'Swahili', 'code' => 'SWA', 'description' => 'A Bantu language spoken in East Africa', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '133', 'name' => 'Swedish', 'code' => 'SWE', 'description' => 'A North Germanic language spoken in Sweden', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '134', 'name' => 'Tagalog', 'code' => 'TGL', 'description' => 'An Austronesian language spoken in the Philippines', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '135', 'name' => 'Tahitian', 'code' => 'TAH', 'description' => 'A Polynesian language spoken in Tahiti', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '136', 'name' => 'Tamil', 'code' => 'TAM', 'description' => 'A Dravidian language spoken in India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '137', 'name' => 'Tatar', 'code' => 'TAT', 'description' => 'A Turkic language spoken in Russia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '138', 'name' => 'Telugu', 'code' => 'TEL', 'description' => 'A Dravidian language spoken in India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '139', 'name' => 'Thai', 'code' => 'THA', 'description' => 'A Kra-Dai language spoken in Thailand', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '140', 'name' => 'Tibetan', 'code' => 'TIB', 'description' => 'A Sino-Tibetan language spoken in Tibet', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '141', 'name' => 'Tigrinya', 'code' => 'TIG', 'description' => 'A Semitic language spoken in Eritrea and Ethiopia', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '142', 'name' => 'Tonga', 'code' => 'TON', 'description' => 'A Polynesian language spoken in Tonga', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '143', 'name' => 'Turkish', 'code' => 'TUR', 'description' => 'A Turkic language spoken in Turkey', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '144', 'name' => 'Turkmen', 'code' => 'TUK', 'description' => 'A Turkic language spoken in Turkmenistan', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '145', 'name' => 'Ukrainian', 'code' => 'UKR', 'description' => 'An East Slavic language spoken in Ukraine', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '146', 'name' => 'Urdu', 'code' => 'URD', 'description' => 'An Indo-Aryan language spoken in Pakistan and India', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '147', 'name' => 'Uzbek', 'code' => 'UZB', 'description' => 'A Turkic language spoken in Uzbekistan', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '148', 'name' => 'Vietnamese', 'code' => 'VIE', 'description' => 'A Kra-Dai language spoken in Vietnam', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '149', 'name' => 'Welsh', 'code' => 'WEL', 'description' => 'A Celtic language spoken in Wales', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '150', 'name' => 'Wolof', 'code' => 'WOL', 'description' => 'A Niger-Congo language spoken in Senegal', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '151', 'name' => 'Xhosa', 'code' => 'XHO', 'description' => 'A Bantu language spoken in South Africa', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '152', 'name' => 'Yiddish', 'code' => 'YID', 'description' => 'A High German-derived language spoken by Ashkenazi Jews', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '153', 'name' => 'Yoruba', 'code' => 'YOR', 'description' => 'A Niger-Congo language spoken in Nigeria', 'direction' => '', 'default' => '', 'status' => 'A'),
    array('id' => '154', 'name' => 'Zulu', 'code' => 'ZUL', 'description' => 'A Bantu language spoken in South Africa', 'direction' => '', 'default' => '', 'status' => 'A')
));
    }
}
