@php
    use Carbon\Carbon;
    use App\Models\State;
@endphp
@extends('admin.layout.header')
<!-- Specify content -->
@section('content')
    <style>
        @media (min-width: 1200px) {
            .modal-xxl {
                --bs-modal-width: 1502px;
            }
        }
    </style>
    @if ($message = Session::get('success'))
        <div class="alert alert-primary alert-dismissible fade show">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close"><span><i
                        class="fa-solid fa-xmark"></i></span>
            </button>
            <strong>Success!</strong> {{ $message }}
        </div>
    @endif
    <div class="col-xl-12 events">
        <div class="card dz-card" id="accordion-four">
            <div class="card-header">
                <h4 class="card-title"> Client Qualifications Register (CQR) Report</h4>
            </div>
            <div class="card-block p-3">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <!--End for WWB-400-->
                        <div style="float:right">
                        <input type="radio" name="groupView" checked="" onclick="location.href='CQRreport'" checked> New Report &nbsp;&nbsp;
                        <input type="radio" name="groupView" onclick="location.href='CQRreporthistory'" checked> Report History</div>
                    </div>
            </div>
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Date From - Date To	</th>
                        <th scope="col">CQR XML Files</th>
                        <th scope="col">Generated On</th>
                        <th scope="col"> Generated By</th>
                        <th scope="col">Reporting State </th>
                      </tr>
                    </thead>
                    <tbody>
                        @foreach ($CQR as $item)
                        @php
                            $state = State::where('id',$item->state)->first();
                        @endphp
                        <tr>
                            <th>{{ $item->from }} - {{ $item->to }}</th>
                            <td><a href="{{ $item->cqr_xml }}" download>{{ $item->cqr_xml }}</a></td>
                            <td>{{ $item->created_at }}</td>
                            <td>{{ $item->generated_by }}</td>
                            @if ($state != null)
                            <td>{{ $state->name }}</td>
                            @endif
                          </tr>
                        @endforeach
                     
                    </tbody>
                  </table>
            </div>
        </div>
    @stop
    @push('scripts')
    @endpush
